CREATE TABLE soundmapping.raw2 (
	`index` int,
    Activity_0 double,
    Activity_1 double,
    Activity_2 double,
    Activity_3 double,
    `Microphone Number` text,
    `Source ID_0` int,
    `Source ID_1` int,
    `Source ID_2` int,
    `Source ID_3` int,
    `Time` text ,
    `Time In Seconds` double,
    `Timestamp` text,
    X_0 double,
    Y_0 double,
    Z_0 double,
    X_1 double,
    Y_1 double,
    Z_1 double,
    X_2 double,
    Y_2 double,
    Z_2 double,
    X_3 double,
    Y_3 double,
    Z_3 double
     );